application:
  appName: locadora_passa_tempo

spring:
  application:
    name: locadora_passa_tempo
  datasource:
    url: jdbc:postgresql://localhost:5432/LocadoraPassaTempo?createDatabaseIfNotExist=true
    username: locadora
    password: admin
  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
#  liquibase:
#    change-log: classpath:/db/master.xml
#        drop-first: true
server:
  port: 8080
